name: Delete untagged GHCR images

on:
  workflow_dispatch: # Run manually from the Actions tab

jobs:
  cleanup:
    name: Delete all untagged images
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete untagged GHCR images
        uses: actions/delete-package-versions@v5
        with:
          package-name: "umami" # 👈 change if your GHCR package name differs
          package-type: "container"
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
