name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/umami-software/umami.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Rebase
        run: git rebase upstream/master

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git master --force
